version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555" #for prisma studio
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - app-images:/app/public/uploads
    working_dir: /app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db-data:
  app-images:
